language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ruby-head
  - jruby-head
  - 1.8.7
  - ree
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: Gemfile.rails4.ci
    - rvm: 1.9.2
      gemfile: Gemfile.rails4.ci
    - rvm: jruby-18mode
      gemfile: Gemfile.rails4.ci
    - rvm: rbx-18mode
      gemfile: Gemfile.rails4.ci
    - rvm: ree
      gemfile: Gemfile.rails4.ci
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

gemfile:
  - Gemfile.rails3.ci
  - Gemfile.rails4.ci
